# Generated by Django 3.2.6 on 2021-08-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20210808_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.AlterField(
            model_name='application',
            name='companyName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
