# Generated by Django 3.2.6 on 2021-08-08 20:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20210808_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='applications.application')),
                ('interview_date', models.DateField()),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('duration', models.IntegerField(default=1)),
                ('interview_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='application',
            old_name='companyName',
            new_name='company_name',
        ),
    ]
