# Generated by Django 3.2.6 on 2021-08-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20210808_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
